language: python

python:
  - "3.6"  # 3.7

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres

env:
  - SECRET_KEY=this-should-be-secret

script:
  - python manage.py test
