language: python

python:
  - "3.6"  # 3.7

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD 'test_user';" -U postgres
  - psql -c "ALTER USER test CREATEDB;" -U postgres

env:
  - SECRET_KEY=this-should-be-secret DATABASE_NAME=test_db DATABASE_USER=test_user DATABASE_PASSWORD=test_user DATABASE_HOST=localhost DATABASE_PORT=5432

script:
  - python manage.py test
